# Generated by Django 3.1.1 on 2020-09-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animeinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animeseries',
            options={'verbose_name': 'Anime Series', 'verbose_name_plural': 'Anime Series'},
        ),
        migrations.AlterModelTable(
            name='animeseries',
            table='animeseries',
        ),
    ]
